#!/bin/bash

mkdir /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/quant
mkdir /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/quant/condition1_rep1
mkdir /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/quant/condition2_rep1


kallisto quant -i /home/etudiant8/EtudesCas/EC1_etudiant08/data/reference/Homo_sapiens.GRCh38.cds.all.fa.idx -o /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/quant/condition1_rep1  /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/trimming/trailtrim_paired_condition1_rep1_R1.fastq.gz /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/trimming/trailtrim_paired_condition1_rep1_R2.fastq.gz 1> /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/log/sortie_kallisto_condition1_rep1_R1_R2.txt 2>> /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/log/sortie_kallisto_condition1_rep1_R1_R2.txt


kallisto quant -i /home/etudiant8/EtudesCas/EC1_etudiant08/data/reference/Homo_sapiens.GRCh38.cds.all.fa.idx -o /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/quant/condition2_rep1  /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/trimming/trailtrim_paired_condition2_rep1_R1.fastq.gz /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/trimming/trailtrim_paired_condition2_rep1_R2.fastq.gz 1> /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/log/sortie_kallisto_condition2_rep1_R1_R2.txt 2>> /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/log/sortie_kallisto_condition2_rep1_R1_R2.txt