#!/bin/bash

############### analyse fastqc 
mkdir /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/qc

fastqc /home/etudiant8/EtudesCas/EC1_etudiant08/data/raw_data/condition1_rep1_R1.fastq.gz -o /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/qc 1> /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/log/sortie_fastqc_condition1_rep1_R1.txt 2>> /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/log/sortie_fastqc_condition1_rep1_R1.txt

fastqc /home/etudiant8/EtudesCas/EC1_etudiant08/data/raw_data/condition2_rep1_R1.fastq.gz -o /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/qc 1> /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/log/sortie_fastqc_condition2_rep1_R1.txt 2>> /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/log/sortie_fastqc_condition2_rep1_R1.txt

fastqc /home/etudiant8/EtudesCas/EC1_etudiant08/data/raw_data/condition2_rep1_R2.fastq.gz -o /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/qc 1> /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/log/sortie_fastqc_condition2_rep1_R2.txt 2>> /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/log/sortie_fastqc_condition2_rep1_R2.txt

fastqc /home/etudiant8/EtudesCas/EC1_etudiant08/data/raw_data/condition1_rep1_R2.fastq.gz -o /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/qc 1> /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/log/sortie_fastqc_condition1_rep1_R2.txt 2>> /home/etudiant8/EtudesCas/EC1_etudiant08/analyses/log/sortie_fastqc_condition1_rep1_R2.txt